DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS preference;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS mode;
DROP TABLE IF EXISTS fanSpeed;
DROP TABLE IF EXISTS health;
DROP TABLE IF EXISTS cleaning;
DROP TABLE IF EXISTS light;
DROP TABLE IF EXISTS sound;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS airTemperature;
DROP TABLE IF EXISTS airHumidity;
DROP TABLE IF EXISTS powerStatus;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE preference (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temperature REAL NOT NULL,
  mode TEXT NOT NULL, 
  fanSpeed TEXT NOT NULL, 
  light TEXT NOT NULL, 
  sound TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE schedule (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  preference_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  turnOnTime TEXT NOT NULL,
  turnOffTime TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (preference_id) REFERENCES preference (id)
);

CREATE TABLE powerStatus (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL
);

CREATE TABLE airTemperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE airHumidity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE mode (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL
);

CREATE TABLE fanSpeed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL
);

CREATE TABLE health (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value INTEGER NOT NULL
);

CREATE TABLE cleaning (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cleaning_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL
);

CREATE TABLE light (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL,
  intensity INTEGER
);

CREATE TABLE sound (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL,
  volume INTEGER
);


INSERT INTO sound(value, volume) VALUES ("ON", 50);

INSERT INTO light(value, intensity) VALUES ("ON", 50);

INSERT INTO powerStatus(value) VALUES ("ON");

INSERT INTO cleaning(value) VALUES ("STOP");

INSERT INTO mode(type) VALUES ("AUTO");

INSERT INTO fanSpeed(value) VALUES ("MEDIUM");

INSERT INTO health(value) VALUES (10);